### ISSUE TITLE
执行wails build 失败 

### ISSUE THREAD

**Issue by YQHan** [yann0917/dedao-gui#1]
<img width="546" alt="Screenshot 2023-02-22 at 09 58 26" src="https://user-images.githubusercontent.com/9411155/220501396-794f7462-6eeb-4761-b1d7-98920d5a0944.png">

如图报错

**Comment by yann0917** [comment]
我本地执行没有问题，或许你执行一下 `wails dev` 试试看，或者参考这个 [issue](https://github.com/wailsapp/wails/issues/1796)

**Comment by YQHan** [comment]
> 我本地执行没有问题，或许你执行一下 `wails dev` 试试看，或者参考这个 [issue](https://github.com/wailsapp/wails/issues/1796)
<img width="1033" alt="Screenshot 2023-02-23 at 14 31 30" src="https://user-images.githubusercontent.com/9411155/220835290-d0b65b66-c1bf-4906-bcde-c0f8c56195a9.png">


执行wails dev 也是127报错
