### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ly-create** [yann0917/dedao-gui#13]
XML syntax error on line 2776: invalid UTF-8

[XML文件中包含了一些不符合UTF-8编码规范的字符](https://stackoverflow.com/questions/2507608/error-input-is-not-proper-utf-8-indicate-encoding-using-phps-simplexml-lo)

**Comment by yann0917** [comment]
烦请告知是哪本电子书，一般来讲这个问题是电子书里存在非 UTF-8 编码字造成的，可以在 APP 里纠错反馈给得到。

**Comment by ly-create** [comment]
禅思想史讲义

**Comment by yann0917** [comment]
> 禅思想史讲义

确认是电子书的问题，出问题的内容如下：P144 页这里官方也没显示出来，您可以长按有问题的地方，纠错反馈给官方。

<img width="280" alt="image" src="https://github.com/yann0917/dedao-gui/assets/25262709/cf805009-ea2c-4124-98ab-7eff95d41748">

<img width="577" alt="image" src="https://github.com/yann0917/dedao-gui/assets/25262709/10372661-6253-4b3a-95f9-41b88acac2ef">
