### ISSUE TITLE
无法下载课程

### ISSUE THREAD

**Issue by ali-biubiu** [yann0917/dedao-gui#2]
登录以后，选择课程tab，点击下载，选择Makrdown格式，提示没有购买。进入章节列表，单独下载文稿是可以正常下载的。

<img width="935" alt="image" src="https://user-images.githubusercontent.com/5909801/229512568-52df8d2b-3e7a-4121-b8a8-49b839aa92ec.png">

**Comment by yann0917** [comment]
> 登录以后，选择课程tab，点击下载，选择Makrdown格式，提示没有购买。进入章节列表，单独下载文稿是可以正常下载的。
> 
> <img alt="image" width="935" src="https://user-images.githubusercontent.com/5909801/229512568-52df8d2b-3e7a-4121-b8a8-49b839aa92ec.png">

最好单独下载章节，否则会触发得到的反爬虫机制，这个时候，登录一下网页版，图片验证之后，再登录这个软件就好了。

**Comment by ali-biubiu** [comment]
明白了。顺便问一下，下载pdf或者epub的时候也是要集中下载大量资源的，这是如何绕过得到的反爬虫机制的？

**Comment by yann0917** [comment]
> 明白了。顺便问一下，下载pdf或者epub的时候也是要集中下载大量资源的，这是如何绕过得到的反爬虫机制的？

下载pdf或者epub的时候只是谋一本书，同一个 api ，请求参数不同而已，官方也会一次请求很多接口，这个好像没有反爬机制。
