### ISSUE TITLE
大神，能帮忙看看问题出现在哪吗

### ISSUE THREAD

**Issue by hhzhouj** [yann0917/dedao-gui#20]
PS C:\Users\Administrator\myproject\dedao-gui-main\dedao-gui-main> wails build
Wails CLI v2.7.1

# Build Options

Platform(s)        | windows/amd64
Compiler           | C:\Program Files\Go\bin\go.exe
Skip Bindings      | false
Build Mode         | production
Devtools           | false
Frontend Directory | C:\Users\Administrator\myproject\dedao-gui-main\dedao-gui-main\frontend
Obfuscated         | false
Skip Frontend      | false
Compress           | false
Package            | true
Clean Bin Dir      | false
LDFlags            |
Tags               | []
Race Detector      | false
Warning: go.mod is using Wails '2.6.0' but the CLI is 'v2.7.1'. Consider updating your project's `go.mod` file.

# Building target: windows/amd64

  • Generating bindings:   ERROR
          go: downloading golang.org/x/exp v0.0.0-20231006140011-7918f672742d
          go: downloading github.com/labstack/echo/v4 v4.11.2
          go: downloading github.com/go-ole/go-ole v1.3.0
          go: downloading github.com/google/uuid v1.3.1
          go: github.com/PuerkitoBio/goquery@v1.8.1 requires
                github.com/andybalholm/cascadia@v1.3.1: Get "https://proxy.golang.org/github.com/andybalholm/cascadia/@v/v1.3.1.mod": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

          exit status 1

  ERROR
          go: downloading golang.org/x/exp v0.0.0-20231006140011-7918f672742d
          go: downloading github.com/labstack/echo/v4 v4.11.2
          go: downloading github.com/go-ole/go-ole v1.3.0
          go: downloading github.com/google/uuid v1.3.1
          go: github.com/PuerkitoBio/goquery@v1.8.1 requires
                github.com/andybalholm/cascadia@v1.3.1: Get "https://proxy.golang.org/github.com/andybalholm/cascadia/@v/v1.3.1.mod": dial tcp 142.251.43.17:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

          exit status 1

**Comment by yann0917** [comment]
下载依赖超时了，魔法上网，或者设置一下 goproxy 终端执行：`go env -w GOPROXY=https://goproxy.cn,direct`
