### ISSUE TITLE
Mac下打包出来的dedao-gui.app没有图标

### ISSUE THREAD

**Issue by WangDongYao** [yann0917/dedao-gui#21]
go版本：1.21.5
node版本：v21.5.0
wails版本：v2.7.1
macOS：12.7.2
<img width="297" alt="Xnip2024-01-01_10-35-32" src="https://github.com/yann0917/dedao-gui/assets/9822643/0d13ae28-d57d-4cda-9721-8d890adca6a1">

**Comment by yann0917** [comment]
wails更新导致的，我更新一下，参考 https://wails.io/zh-Hans/docs/guides/troubleshooting#mac-%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F%E6%97%A0%E6%95%88
