### ISSUE TITLE
无法登录, 没有QR Code, 烦请帮忙。 感恩！

### ISSUE THREAD

**Issue by Ethanww3** [yann0917/dedao-gui#22]
大佬, 有个问题, 桌面版本没有QR code 去scan, 你在教程里说

本应用上登录后再登录官方网页版会导致保存的 cookie 失效，使用 rm -rf ~/.config/dedao/config.json 删除配置信息后重新登陆本应用即可。

我在node, npm, go 里输入这个指令都说找不到文件, 自己搜了C盘也没有找到这个 .config/dedao/config.json

请问如何解决， 感激不尽！

**Comment by Ethanww3** [comment]
我用的是windows系统 大佬

**Comment by yann0917** [comment]
参考 issue #7
