### ISSUE TITLE
你好 大佬, Error Main. go : 18 : 12 Pattern all frontend/dist: no matching files found

### ISSUE THREAD

**Issue by Ethanna166166** [yann0917/dedao-gui#23]
大佬遇到以下错误：
Error Main. go : 18 : 12 Pattern all frontend/dist: no matching files found

这里是截图：
![error](https://github.com/yann0917/dedao-gui/assets/80655771/c178b343-9ca6-4c54-8e48-5a8f91b2f81f)

请问如何解决,  感谢！

**Comment by yann0917** [comment]
大概率是你本地 go 版本太低了，不支持embed, wails 支持的最低版本是 Go 1.18+

**Comment by Ethanna166166** [comment]
> 大概率是你本地 go 版本太低了，不支持embed, wails 支持的最低版本是 Go 1.18+

感谢大佬回复, 我检查了一下, Go版本是1.21.6, 
![go version](https://github.com/yann0917/dedao-gui/assets/80655771/5ff74a2d-a542-4972-8e5d-6d195fdf2152)



另外执行wails doctor显示 如下
![doctor](https://github.com/yann0917/dedao-gui/assets/80655771/1073a851-3ca6-4989-8c76-ad90486accbb)

**Comment by yann0917** [comment]
试一下 `wails dev` 呢？

**Comment by Ethanna166166** [comment]
> 试一下 `wails dev` 呢？

大佬, 搞定了！！  我更新了一下windows 再试就成功安装了。 再次感谢。 祝大佬 新年快乐, 财源滚滚！！
