### ISSUE TITLE
您好 请问我该怎么做

### ISSUE THREAD

**Issue by youloust** [yann0917/dedao-gui#25]
Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend:
    > frontend@0.0.0 build
    > vue-tsc --noEmit && vite build

    'vue-tsc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
    ���������ļ���

  ERROR   exit status 1

  ERROR   exit status 1
![Uploading e8f2565c2b6b8897c649c9e7bd64641.png…]()

**Comment by yann0917** [comment]
你提供的信息是乱码，根本看不出来任何问题，大概率是本地电脑没有相应的命令。
