### ISSUE TITLE
登录时候生成二维码失败

### ISSUE THREAD

**Issue by lazeman** [yann0917/dedao-gui#29]
很长时间不用，需要重新 登录，就一直是生成失败了。具体是什么原因？
![微信截图_20240416152338](https://github.com/yann0917/dedao-gui/assets/11134149/9450a7f8-486d-4a13-b487-30f49efd65af)

此外，课程和电子书能不能增加一个搜索功能啊，经常找不到想下载的资源，谢谢！

**Comment by yann0917** [comment]
第一个问题，参考 #7 
第二个，目前没有加搜索功能的计划。

**Comment by yann0917** [comment]
得到 官方 web 端，已购页并没有搜索功能。
