### ISSUE TITLE
咨询：编译完的app双击没有响应

### ISSUE THREAD

**Issue by ali-biubiu** [yann0917/dedao-gui#3]
编译完的app通过双击的方式无法执行，只能通过命令行执行./dedao-gui.app/Contents/MacOS/dedao-gui的方式执行。

**Comment by yann0917** [comment]
找到问题了，我记录一下原因：代码中使用了相对路径，但是在MAC上是不行的；只需要把相对路径改为绝对路径即可！参考[这里](https://blog.csdn.net/u014220518/article/details/100609843)

**Comment by GreatBallacuda** [comment]
我这现在还是需要命令行启动。。怎么回事？
