### ISSUE TITLE
不支持Apple芯片？

### ISSUE THREAD

**Issue by clover2024** [yann0917/dedao-gui#30]
M3 pro芯片编译完成打开闪退，换用intel芯片Macbook解决，似乎有这个缺陷

**Comment by yann0917** [comment]
> M3 pro芯片编译完成打开闪退，换用intel芯片Macbook解决，似乎有这个缺陷

没有 m3 芯片, 也没适配过，m1 芯片上倒是可以。

**Comment by yann0917** [comment]
使用 `wails dev`  看下有没有什么错误信息，感觉是wails 的bug

**Comment by jessy4002** [comment]
<img width="480" alt="image" src="https://github.com/yann0917/dedao-gui/assets/103703677/9cdedd99-cd19-486f-bcb2-df95159e892f">
m1的报错什么原因吗？

**Comment by jessy4002** [comment]
> 使用 `wails dev` 看下有没有什么错误信息，感觉是wails 的bug

我运行就报错了，这个图：
<img width="480" alt="image" src="https://github.com/yann0917/dedao-gui/assets/103703677/230b1d8b-5d0d-43f1-b523-011b9d8b8532">

**Comment by yann0917** [comment]
我这边用 m3 pro 没有闪退的情况。只是遇到了这个问题 `app is damaged and can’t be opened. You should move it to the Trash.
` , 然后执行了下面的命令就可以了。

`sudo xattr -rd com.apple.quarantine /Applications/dedao-gui.app` 

硬件信息如下：
<img width="1008" alt="image" src="https://github.com/yann0917/dedao-gui/assets/25262709/83840bcc-c087-4dc3-b8e8-868e94f87807">
执行之后打开如下：
<img width="1280" alt="image" src="https://github.com/yann0917/dedao-gui/assets/25262709/bc86a8e2-5087-4e89-95aa-9b1d3bd4bf19">
