### ISSUE TITLE
能增加另外一种epub格式吗【把每章的注释放于每章后面】

### ISSUE THREAD

**Issue by 576298** [yann0917/dedao-gui#31]
现在的epub的注释都穿插在正文里了
如果某本的注释比较多，感觉有点影响阅读

比如这本【置身事内】
能增加另外一种epub格式吗【每章的注释放于每章后面】
【注释可以互相跳转：
把【注】这个图片换成【字体大一点】的1 2 3 4 5 6.......的数字【带超链接】，
具体注释依次列于每章后面，依次加上【字体大一点】的1 2 3 4 5 6.......的数字【也带超链接】，
点击1 2 3 4 5 6.......数字可以来回互相跳转

就像下面这个epub文件的注释一样
epub下载地址：
https://thanks.lanzn.com/i3nA71xjdxpa

另外1本【撒马尔罕的金桃】注释倒是1 2 3 4 5 6.......的这种形式，但是好像无法互相跳转

**Comment by yann0917** [comment]
可以，但是不建议这样做，还是要尊重原书样式。有些书的注释是在每章最后，有些是在「注」图标上，有些是1,2,3,4这样的来回跳转。原书是什么样的注释格式，跟原书保持一致就行。
