### ISSUE TITLE
扫码登录的二维码无法正常显示（加载失败）

### ISSUE THREAD

**Issue by liyannow** [yann0917/dedao-gui#32]
环境：Windows
系统：Windows 11
go版本：go1.12.5
dedao-gui版本：最新
问题出现频率：从过年至今

不知道为什么，GUI端的二维码不能显示（dedao-dl能够显示二维码并且正常使用）。

同时打开dedao.cn，官网的二维码能够正常显示。

但是客户端的GUI就无法显示，希望作者能够帮忙找到问题。

![image](https://github.com/yann0917/dedao-gui/assets/23151016/ea9ec21f-8cb2-42a1-9734-93c3031e8549)

**Comment by yann0917** [comment]
参考 #7

**Comment by liyannow** [comment]
谢谢，已经解决，文件在C:\tmp\dedao（如果程序在D盘就改在D） 中，找了好久才找到。
