### ISSUE TITLE
请问批量下载电子书+更改命名规则有计划吗

### ISSUE THREAD

**Issue by qadan72** [yann0917/dedao-gui#33]
作者你好，请问：
1，批量下载电子书
2，更改电子书命名规则：比如在电子书后面添加出版时间，并删除电子书ID

这两个需求有计划吗？

**Comment by yann0917** [comment]
第一个不建议，批量有可能导致接口异常，导致下载失败。
第二个关于命名规则，见仁见智，可以自行修改代码实现，在 [227行](https://github.com/yann0917/dedao-gui/blob/66a634262296b710f9c91937e264a0b5d2e3d706/backend/app/download.go#L227) 附近
