### ISSUE TITLE
无法保存文件

### ISSUE THREAD

**Issue by ali-biubiu** [yann0917/dedao-gui#4]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/5909801/232742245-3c4adbed-b6fd-49a8-ada4-3f376ea28308.png">
app运行的方式无法下载文件，提示信息如上。通过命令行执行./dedao-gui.app/Contents/MacOS/dedao-gui，可以正常下载。

**Comment by yann0917** [comment]
确实有这个问题，一开始只是做了命令行版本，加了界面之后，下载文件保存位置需要提前设置，而不是命令所在目录才行。

**Comment by liamli** [comment]
> 确实有这个问题，一开始只是做了命令行版本，加了界面之后，下载文件保存位置需要提前设置，而不是命令所在目录才行，我修改一下。

有临时解决方案吗？

**Comment by yann0917** [comment]
> > 确实有这个问题，一开始只是做了命令行版本，加了界面之后，下载文件保存位置需要提前设置，而不是命令所在目录才行，我修改一下。
> 
> 有临时解决方案吗？

直接用 wails dev 启动就可以下载保存了，在当前目录 output 下面

**Comment by yann0917** [comment]
已知下载保存的 bug 请参考 #6
