### ISSUE TITLE
大佬 能否增加一个电子书下载的多选功能

### ISSUE THREAD

**Issue by hewenbo1994** [yann0917/dedao-gui#41]
电子书的文件不会太大，应该可以加一个多选下载的功能吧

**Comment by yann0917** [comment]
电子书提供的是每页的svg 文件， 我根据svg 文件合成的电子书，多选批量下载的话，很可能触发反爬虫机制。一本大部头的书都不太好下载，总是触发反爬。

**Comment by hewenbo1994** [comment]
> 电子书提供的是每页的svg 文件， 我根据svg 文件合成的电子书，多选批量下载的话，很可能触发反爬虫机制。一本大部头的书都不太好下载，总是触发反爬。

那么能否加一个列队呢，下载速度不改变，只是一个多任务列表，然后放在那里慢慢下载
