### ISSUE TITLE
epub注释不兼容其他阅读器

### ISSUE THREAD

**Issue by bookoyo** [yann0917/dedao-gui#45]
通过桌面软件导出的epub文件，

注释重复了，除了正常的弹出注释，

注释内容会单独、直接显示在段落前一段，造成阅读困扰，

经常以为那是正文内容，如图所示
![63ecf408a2f7c0a6200f8e6ce339b67](https://github.com/user-attachments/assets/60c1147d-8157-4d4e-a5d7-cc88b5632fba)

**Comment by bookoyo** [comment]
经过测试，不用桌面端，用win运行生成的epub，也存在一样的注释问题~

**Comment by bookoyo** [comment]
再反馈一下，html的注释没问题，只有epub有这问题~@yann0917

**Comment by yann0917** [comment]
![image](https://github.com/user-attachments/assets/411183c0-4fc8-4fdb-8305-3d115a0dc31e)
我这边复现不出来这个问题，用的是 mac自带的epub 阅读器，能否告知我你用的阅读器是什么？

**Comment by yann0917** [comment]
盲猜可能是epub 阅读器兼容问题

**Comment by bookoyo** [comment]
pc端calibre、手机端epub导入微信读书，还有导入kindle都是这样，我试一下别的阅读器看看（对了，我没说书名你咋找到这本书的~）

**Comment by bookoyo** [comment]
大佬，我试了一下，苹果原生阅读app确实没毛病，

 但其他的都不行（多看阅读、百度云、calibre、掌阅、kindle、Anyview、多个epub在线阅读网站）
 
 不麻烦的话希望大佬稍微改改（安卓狗哭晕在厕所~）

**Comment by yann0917** [comment]
我测试了**多看**和**掌阅**，是可以的，calibre不行没找到兼容方案，其他的没测。

**Comment by bookoyo** [comment]
大佬看图，你是安卓机测试的吗？
![微信图片_20240912103807](https://github.com/user-attachments/assets/7058069b-706c-4e6d-83b7-746b2e53b036)
![微信图片_20240912103759](https://github.com/user-attachments/assets/4ff90d42-9d0d-4f7c-9a96-2b94327726d4)

**Comment by bookoyo** [comment]
> yann0917

滴滴滴滴

**Comment by yann0917** [comment]
> > yann0917
> 
> 滴滴滴滴

![Screenshot_2024-09-12-10-46-27-26_b1995b84b0cf709cff55a579c85c1488.jpg](https://github.com/user-attachments/assets/db47822d-fe95-43c0-9aa1-77dbff54112d)

是安卓版多看

**Comment by bookoyo** [comment]
> > > YANN0917
> > 
> > 
> > 滴滴滴滴
> 
> ![Screenshot_2024-09-12-10-46-27-26_b1995b84b0cf709cff55a579c85c1488.jpg](https://private-user-images.githubusercontent.com/25262709/366701891-db47822d-fe95-43c0-9aa1-77dbff54112d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDk2MzcsIm5iZiI6MTcyNjEwOTMzNywicGF0aCI6Ii8yNTI2MjcwOS8zNjY3MDE4OTEtZGI0NzgyMmQtZmU5NS00M2MwLTlhYTEtNzdkYmZmNTQxMTJkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAyNDg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMjJhZjY2MjI5ZTJhZWU2N2IzZDE2MzZjZWY1YzhiZGUxZTY4MGNiM2M2MTMwNzBkM2EyNGMwYmY2ZWRkNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DPBSR8MxxcqKnSgHbVrbhoh35Bk8ZTlaKDam1X-KroE)
> 
> 是安卓版多看，7.43.5

你是小米自带的多看吗？我这边下载多看的话，最新版本是6.6.0.2

**Comment by yann0917** [comment]
我这边掌阅点击是可以弹出来的，只不过这个注释图标太小了，不知道怎么放大

**Comment by bookoyo** [comment]
> 我这边掌阅点击是可以弹出来的，只不过这个注释图标太小了，不知道怎么放大

大佬，能不能导出一下该版本app，我也是醉了，现在其他平台多看不更新了，只有小米手机能下最新版

**Comment by bookoyo** [comment]
> 我这边掌阅点击是可以弹出来的，只不过这个注释图标太小了，不知道怎么放大

掌阅是哪个版本？

**Comment by bookoyo** [comment]
多看阅读官网下载链接是应用宝的，结果都下架了。。。其他平台也下架了，没下架的止步6.6.2版了

**Comment by yann0917** [comment]
> > 我这边掌阅点击是可以弹出来的，只不过这个注释图标太小了，不知道怎么放大
> 
> 掌阅是哪个版本？

8.1.2(116298)

**Comment by yann0917** [comment]
> 多看阅读官网下载链接是应用宝的，结果都下架了。。。其他平台也下架了，没下架的止步6.6.2版了

我一加手机自带的应用商店下的

**Comment by bookoyo** [comment]
> > > 我这边掌阅点击是可以弹出来的，只不过这个注释图标太小了，不知道怎么放大
> > 
> > 
> > 掌阅是哪个版本？
> 
> 8.1.2(116298)
大佬，小米手机，下了最新版的多看和掌阅（和你一样的版本），但依旧是老问题，我碎了，不知道你这个为啥是正常的

**Comment by yann0917** [comment]
代码是最新的吗，重新构建了吗

**Comment by bookoyo** [comment]
> 代码是最新的吗，重新构建了吗

我去，原来更新了代码。。。我还以为之前的就支持呢，尴尬了
