### ISSUE TITLE
想请问一下这个 wails buid 报错怎么处理

### ISSUE THREAD

**Issue by Xuhaner** [yann0917/dedao-gui#5]
夸夸up主，这个功能真的很需要。个人不是学习开发的，不太能理解这个问题，想请问一下该怎么处理。

dedao-dl login -q
这种方式好像是可以的，但不是界面模块，个人使用起来有些难度。

问题描述：
使用 MacBook Air M2 在 iterm2 中进行 wails build 时，有如下错误信息，想请教一下怎么更改，或者能使用什么方法进行解决。
使用 wails dev 也会报错。

不确定是环境配置问题，还是流程上有错误。

Done.
  • Installing frontend dependencies: Done.
  • Compiling frontend:
    > frontend@0.0.0 build
    > vue-tsc --noEmit && vite build

    src/components/QrLogin.vue(89,1): error TS2322: Type 'Timer' is not assignable to type 'number'.

  ERROR   exit status 2

  ERROR   exit status 2

**Comment by yann0917** [comment]
我本地用的是 M1，没有复现这个问题，有可能是 typescript 版本的问题，参考 [这里](https://blog.csdn.net/zhai_865327/article/details/106457196)

临时解决办法是  将 src/components/QrLogin.vue 89 行 改为 `timeState.timer = window.setInterval(() => {` 试试看，可以的话我更新一下代码。

**Comment by Xuhaner** [comment]
可以用了！非常感谢！
