### ISSUE TITLE
登录二维码无法显示

### ISSUE THREAD

**Issue by ali-biubiu** [yann0917/dedao-gui#7]
操作路径：个人中心 -> 登录，二维码无法加载。
<img width="354" alt="image" src="https://user-images.githubusercontent.com/5909801/233592273-b43ee787-17ea-436c-b602-d47cbef79b2e.png">

**Comment by yann0917** [comment]
是不是登录过网页版？

**Comment by liamli** [comment]
> 是不是登录过网页版？先清理一下 home 目录下的 `.config/dedao/config.json` 文件试试看
> 
> 或者运行 `wails dev` 之后，右键检查元素，清理 storage

.config/dedao/config.json
这个路径是在哪里？ 我的是Mac系统

**Comment by yann0917** [comment]
> > 是不是登录过网页版？先清理一下 home 目录下的 `.config/dedao/config.json` 文件试试看
> > 或者运行 `wails dev` 之后，右键检查元素，清理 storage
> 
> .config/dedao/config.json 这个路径是在哪里？ 我的是Mac系统

home 目录下

**Comment by scootflynn** [comment]
> > 是不是登录过网页版？先清理一下 home 目录下的 `.config/dedao/config.json` 文件试试看
> > 或者运行 `wails dev` 之后，右键检查元素，清理 storage
> 
> 是这个问题。清理之后可以了。

点一下右上角更换账号就可以了

**Comment by GreatBallacuda** [comment]
> 

请问windows 是在用户自己目录下吗 没有找到。。

**Comment by GreatBallacuda** [comment]
> 

找到了 程序我安装在d盘，文件在 D://tmp/config.jason ，删除了重进就好了

**Comment by yann0917** [comment]
这个  issue 出现的次数太多了，手动解决虽然可以，但是终归不方便，我看下登录逻辑里能不能解决这个问题

**Comment by slashkkk** [comment]
能打个包吗，大爷

**Comment by Qee2** [comment]
> > 
> 
> 找到了 程序我安装在d盘，文件在 D://tmp/dedao/config.jason ，删除了重进就好了

我的exe程序在c盘，没想到config.json在d盘。先前我找了大半天……多谢提醒

**Comment by Qee2** [comment]
> > > 
> > 
> > 
> > 找到了 程序我安装在d盘，文件在 D://tmp/dedao/config.jason ，删除了重进就好了
> 
> 我的exe程序在c盘，没想到config.json在d盘。先前我找了大半天……多谢提醒

又搞了一会儿。原来是要删除C:\tmp\dedao目录下的json文件。看来exe程序在哪个盘，就要删除哪个盘的文件
