### ISSUE TITLE
下载电子书时，点击【确认】按钮没有反应

### ISSUE THREAD

**Issue by liamli** [yann0917/dedao-gui#8]
下载电子书时，点击【确认】按钮没有反应。
格式无论选html、epub还是pdf，都没有反应。 

<img width="441" alt="image" src="https://user-images.githubusercontent.com/732607/235047342-e6236c82-3966-46f6-b3f6-ef0c5da55d31.png">

另外，登录二维码无法显示。

**Comment by yann0917** [comment]
暂时没有找到合适的方法向前端传递进度，确实是没有反应的，README 已经备注说明了，『下载均在后台执行，下载完毕弹框会关闭，等待弹窗关闭或者点击确定下载后关闭，均会在后台执行下载程序。』

**Comment by yann0917** [comment]
二维码不显示的问题参考 bug #7

**Comment by yann0917** [comment]
下载时模拟进度条

**Comment by yann0917** [comment]
更优解决方案：使用 [Events事件](https://wails.io/zh-Hans/docs/reference/runtime/events/)
下载时服务端触发事件，前端设置侦听器侦听特定事件。
