### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by d100972** [yann0917/dedao-gui#9]
• Compiling frontend:
    > frontend@0.0.0 build
    > vue-tsc --noEmit && vite build

    src/main.ts(16,9): error TS2345: Argument of type 'Pinia' is not assignable to parameter of type 'Plugin_2'.
      Type 'Pinia' is not assignable to type '{ install: PluginInstallFunction; }'.
        Types of property 'install' are incompatible.
          Type '(app: App<any>) => void' is not assignable to type 'PluginInstallFunction'.
            Types of parameters 'app' and 'app' are incompatible.
......

**Comment by yann0917** [comment]
本地 element-plus 版本不兼容的问题，升级一下看看呢。[参考](https://blog.csdn.net/qq_44723175/article/details/125179428)
